[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tabeva"
version = "0.0.0"
description = "TabEva project"
readme = "README.md"
requires-python = ">=3.12"
authors = [ { name = "" } ]
dependencies = [
    "pandas>=2.0.0",
    "numpy",
    "scipy",
    "matplotlib",
    "seaborn",
    "scikit-learn",
    "lightgbm",
    "shap",
    "joblib",
]

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools.packages.find]
include = ["tabeva*"]
